name: ASP.NET Core CI-CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: [self-hosted, Windows, X64, iis]

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check .NET
        run: dotnet --info

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --output "${{ github.workspace }}\publish" --no-build

      - name: Stop IIS Website
        shell: powershell
        run: |
          Import-Module WebAdministration
          Stop-Website -Name "MyWebApi"

      - name: Deploy to IIS
        shell: powershell
        run: |
          $source = "${{ github.workspace }}\publish"
          $destination = "C:\inetpub\MyWebApi"

          if (!(Test-Path $destination)) {
              New-Item -ItemType Directory -Path $destination -Force
          }

          Get-ChildItem $destination -Force |
              Remove-Item -Recurse -Force

          Copy-Item "$source\*" $destination -Recurse -Force

      - name: Start IIS Website
        shell: powershell
        run: |
          Import-Module WebAdministration
          Start-Website -Name "MyWebApi"

      - name: Deployment Complete
        run: |
          echo "CI/CD deployment completed successfully!"